export enum PokemonType {
    Normal = "normal",
    Fire = "fire",
    Water = "water",
    Grass = "grass",
    Electric = "electric",
    Ice = "ice",
    Fighting = "fighting",
    Poison = "poison",
    Ground = "ground",
    Flying = "flying",
    Psychic = "psychic",
    Bug = "bug",
    Rock = "rock",
    Ghost = "ghost",
    Dark = "dark",
    Dragon = "dragon",
    Steel = "steel",
    Fairy = "fairy",
}

export enum PokemonGeneration {
    GenerationI = "generation-i",
    GenerationII = "generation-ii",
    GenerationIII = "generation-iii",
    GenerationIV = "generation-iv",
    GenerationV = "generation-v",
    GenerationVI = "generation-vi",
    GenerationVII = "generation-vii",
    GenerationVIII = "generation-viii",
}

export enum PokemonGenerationExtended {
    GenerationI = "First Generation",
    GenerationII = "Second Generation",
    GenerationIII = "Third Generation",
    GenerationIV = "Fourth Generation",
    GenerationV = "Fifth Generation",
    GenerationVI = "Sixth Generation",
    GenerationVII = "Seventh Generation",
    GenerationVIII = "Eighth Generation",
}

export enum PokemonTarget {
    SpecificMove = "specific-move",
    SelectedPokemonMeFirst = "selected-pokemon-me-first",
    Ally = "ally",
    UsersField = "users-field",
    UserOrAlly = "user-or-ally",
    OpponentsField = "opponents-field",
    User = "user",
    RandomOpponent = "random-opponent",
    AllOtherPokemon = "all-other-pokemon",
    SelectedPokemon = "selected-pokemon",
    AllOpponents = "all-opponents",
    EntireField = "entire-field",
    UserAndAllies = "user-and-allies",
    AllPokemon = "all-pokemon",
    AllAllies = "all-allies",
}

export enum PokemonTargetExtended {
    SpecificMove = "Specific Move",
    SelectedPokemonMeFirst = "Specific Move (Me First)",
    Ally = "Ally",
    UsersField = "Users Field",
    UserOrAlly = "User or Ally",
    OpponentsField = "Opponents Field",
    User = "User",
    RandomOpponent = "Random Opponent",
    AllOtherPokemon = "All Other Pokemon",
    SelectedPokemon = "Selected Pokemon",
    AllOpponents = "All Opponents",
    EntireField = "Entire Field",
    UserAndAllies = "User and Allies",
    AllPokemon = "All Pokemon",
    AllAllies = "All Allies",
}
